jus/urls.py
from django.conf.urls import url
#from django.contrib import admin
from jus import views

urlpatterns = [
    url(r'^$',views.list_jus, name='list_jus' ),
    url(r'^categories$',views.list_categories, name='list_categories' ),
    url(r'^(\d+)/$',views.view_ju, name='view_ju' ),
    url(r'^new/$',views.new_ju, name='new_ju' ),
    url(r'^new/p_id=(?P<p_id>\d+)/$',views.new_ju, name='new_ju' ),
    url(r'^location/$',views.new_location, name='new_location' ),
    url(r'^location/(\d+)/$',views.view_location, name='view_location' ),
    url(r'^location/follow/(\d+)/$',views.follow, name='follow' ),
    url(r'^location/unfollow/(\d+)/$',views.unfollow, name='unfollow' ),
]

lists/urls.py
from django.conf.urls import url
#from django.contrib import admin
from lists import views

urlpatterns = [
    url(r'^new$',views.new_list, name='new_list' ),
    url(r'^(\d+)/$',views.view_list, name='view_list' ),
    url(r'^view_order/(\d+)/$',views.view_order, name='view_order' ),
    url(r'^new_order/(\d+)/$',views.new_order, name='new_order' ),
    url(r'^users/(.+)/$',views.my_lists, name='my_lists' ),
    url(r'^loadusers/(\d+)/$',views.load_users, name='load_users' ),
    url(r'^order/(\d+)/$',views.order, name='order' ),
    url(r'^next_ju/(\d+)/$',views.next_ju, name='next_ju' ),
    url(r'^category$',views.category, name='category' ),
    url(r'^next_category/(\d+)/$',views.next_category, name='next_category' ),
]

superlists/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
from lists import views as list_views
from lists import urls as list_urls
from jus import urls as ju_urls
from accounts import urls as account_urls
from wechat import urls as wechat_urls

urlpatterns = [
    url(r'^$',list_views.home_page, name='home' ),
    url(r'^lists/', include(list_urls) ),
    url(r'^jus/', include(ju_urls) ),
    url(r'^accounts/', include(account_urls) ),
    url(r'^wechat/', include(wechat_urls) ),
]

lists/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
# from datetime import timedelta
from django.utils import timezone
import json
import shlex
import re
from json.decoder import JSONDecodeError
from decimal import Decimal

class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='lists_owned')
    agent = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='lists_agented')
    ju = models.ForeignKey('jus.Ju', blank=True, null=True)
    text = models.CharField(default='', max_length=140, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def name(self):
        if self.ju:
            return "{:%Y-%m-%d %H:%M}@{}~{}（{}）".format(
                timezone.localtime(self.created_at), 
                self.ju.address,
                self.ju.stop_date,
                self.ju.status
            )
        return "{:%Y-%m-%d %H:%M}@{}".format(
            timezone.localtime(self.created_at), 
            #self.created_at + timedelta(hours=8), 
            self.item_set.first().text
        )
    @property
    def total_cost(self):
        if self.ju:
            return sum(i.cost for i in self.item_set.filter(name__in = self.ju.items.keys()))
        else:
            return sum(i.cost for i in self.item_set.all())
        return None
    @property
    def items_to_text(self):
        return ';'.join(['{}:{:.2f}'.format(i.name,i.qty).upper() for i in self.item_set.all()])

    @property
    def qtys_by_ju(self):
        qtys=[]
        if self.ju.items:
            for k in sorted(self.ju.items.keys()):
                try:
                    qty = Item.objects.get(list=self, text__istartswith=k).qty
                except:
                    qty = '' 
                qtys.append(qty)
        return qtys

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None, agent=None, ju=None):
        list_ = List(owner=owner, agent=agent, ju=ju)
        list_.full_clean()
        list_.save()
        item = Item(text=first_item_text, list=list_)
        item.save()
        return list_



class Item(models.Model):
        
    text = models.CharField(default='', max_length=140)
    list = models.ForeignKey(List, default=None)
    name = models.CharField(default='', max_length=140)
    qty =  models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=2)
    price =  models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=2)
    def save(self):
        self.parse_text()
        super(Item, self).save()

    def parse_text(self):
        units = shlex.split(self.text)
        last_index = len(units) - 1
        last_n = None
        prior_n = None
        try:
            if last_index >= 1:
                last_n = Decimal(units[last_index])
            if last_index >= 2:
                prior_n = Decimal(units[last_index - 1])
        except Exception as e:
            print('----units:{},exception:{}'.format(units,e))
            pass
        if self.list.ju:
            if last_n != None:
                self.name = re.sub(r'\s+[-+]?[0-9]\d*(\.\d+)?\s*$','', self.text).upper()
                self.qty = last_n
            else:
                self.name = self.text.upper()
            try:
                self.price = self.list.ju.items[self.name]['price']
            except:
                self.price = 0
        elif last_n != None:
            if prior_n!=None:
                self.price = last_n
                self.qty = prior_n
                self.name = re.sub(r'\s+[-+]?[0-9]\d*(\.\d+)?\s+[-+]?[0-9]\d*(\.\d+)?\s*$','', self.text).upper()
            else:
                self.qty = last_n
                self.name = re.sub(r'\s+[-+]?[0-9]\d*(\.\d+)?\s*$','', self.text).upper()
        else:
            self.name = self.text.upper()

    @property
    def cost(self):
        if self.qty and self.price:
            return self.qty*self.price
        return 0


    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text
    pass

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List
from jus.models import Ju
from lists.forms import ExistingListItemForm, NewListForm, ListForm, NewOrderForm
from jus.forms import UsersForm
from accounts.forms import EmailInputForm
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.db.models import Q
import csv
from wechat.views import oauth
NEED_TO_LOGIN_ERROR = "别着急，先登录再凑单！"
User = get_user_model()

def view_order(request, list_id):
    list_ = List.objects.filter(id = list_id).first()
    if (not list_) or (not list_.owner) or (not list_.ju):
        return redirect(reverse('home'))
    if request.user != list_.owner and request.user != list_.agent:
        return redirect(reverse('home'))

    orders = List.objects.filter(Q(ju=list_.ju) & (Q(owner=request.user)|Q(agent=request.user))) 

    form = ExistingListItemForm(for_list = list_)
    if not list_.ju.can_order(request.user):
        form.fields['text'].widget.attrs['readonly'] = True 

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            if form.save():
                return redirect(list_)
    return render(
        request, 
        'view_order.html', 
        { 'list': list_,'current_ju': list_.ju,  'form': form, 'orders': orders}
    )

def next_category(request, ju_id):
    current_ju = Ju.objects.filter(id=ju_id).first()
    if current_ju:
        if request.user.is_authenticated:
            next_ = request.user.next_ju(current_ju, ju_type='category')
        else:
            next_ = current_ju.next(ju_type='category')
        if next_:
            return render(
                request, 
                'view_category.html', 
                { 'current_ju': next_ }
            )

    return category(request)

@oauth
def category(request):
    current_ju = Ju.active_ju(ju_type='category')
    return render(
        request, 
        'view_category.html', 
        { 'current_ju': current_ju }
    )


def order(request, ju_id):
    try:
        current_ju = Ju.objects.get(id=ju_id)
    except :
        if request.user.is_authenticated:
            current_ju = request.user.active_ju()
        else:
            current_ju = Ju.active_ju()
        return render_home_page(request, current_ju)

    if request.user.is_authenticated :
        # 通过new_order可以把owner的代理人改成自己，当然可以用来取消别人对自己的代理。
        if request.method == 'POST':
            form_list = ListForm(depart_name=request.user.depart_name, data=request.POST)
            if form_list.is_valid():
                owner = form_list.cleaned_data['owner'] or request.user
                list_ = List.objects.filter(ju=current_ju, owner=owner).first()
                if list_: 
                    if list_.agent != request.user:
                        list_.agent = request.user
                        list_.save()
                    return view_order(request, list_.id)
            return new_order(request, current_ju.id)
        list_ = List.objects.filter(ju=current_ju, owner=request.user).first()
        if not list_:
            list_ = List.objects.filter(ju=current_ju, agent=request.user).first()
        if list_:
            return view_order(request, list_.id)
    return new_order(request, current_ju.id)

            
def new_order(request, ju_id):
    try:
        current_ju = Ju.objects.get(id=ju_id)
    except :
        if request.user.is_authenticated:
            current_ju = request.user.active_ju()
        else:
            current_ju = Ju.active_ju()
        return render_home_page(request, current_ju)

    depart_name = None
    form = NewOrderForm()
    if not current_ju.can_order(request.user):
        form.fields['text'].widget.attrs['readonly'] = True 
    
    if request.user.is_authenticated :
        depart_name=request.user.depart_name
        form_list = ListForm(depart_name=depart_name)
        # form_list.fields['owner'].initial = request.user
        if request.method == 'POST':
            form = NewOrderForm(data=request.POST)
            form_list = ListForm(depart_name=depart_name, data=request.POST)
            if form.is_valid() and form_list.is_valid():
                owner = form_list.cleaned_data['owner'] or request.user
                list_ = form.save(
                    owner=owner,
                    agent=request.user,
                    ju=current_ju
                )
                if list_:
                    return redirect(list_)
        return render(
            request, 
            'new_order.html', 
            {'form': form, 'form_list': form_list, 'current_ju': current_ju}
        )

    email_input_form = EmailInputForm()
    if request.method == 'POST':
        form = NewOrderForm(data=request.POST)
        form.add_error('text',NEED_TO_LOGIN_ERROR)
    return render(
        request, 
        'new_order.html', 
        {'form': form,  'current_ju': current_ju, 'email_input_form': email_input_form }
    )
def my_lists(request, email):
    try:
        owner = User.objects.get(email=email)
        return render(request, 'my_lists.html', {'owner': owner})
    except User.DoesNotExists:
        return redirect('/')
@oauth
def home_page(request):
    if request.user.is_authenticated:
        current_ju = request.user.active_ju()
    else:
        current_ju = Ju.active_ju()

    if request.user.is_authenticated and current_ju:
        return order(request, current_ju.id)
    return render_home_page(request, current_ju)

def render_home_page(request, ju):
    form = NewListForm()
    form.fields['text'].widget.attrs['placeholder'] = '试试看：橙子1斤 2 2.5'
    if request.user.is_authenticated:
        return render(request, 'home.html', {'form': form, 'first_ju': ju})
    email_input_form = EmailInputForm()
    return render(request, 'home.html', {'form': form, 'first_ju': ju, 'email_input_form': email_input_form})
def new_list(request):
    form = NewListForm(data=request.POST)
    form.fields['text'].widget.attrs['placeholder'] = '怎么填都行'
    if form.is_valid():
        list_ = form.save(owner=request.user if request.user.is_authenticated else None)
        if list_:
            return redirect(list_)
    return render(request, 'home.html', {'form': form })


def next_ju(request, ju_id):
    current_ju = Ju.objects.filter(id=ju_id).first()
    if current_ju:
        if request.user.is_authenticated:
            next_ = request.user.next_ju(current_ju)
        else:
            next_ = current_ju.next()
        if next_:
            return order(request, next_.id)
    if request.user.is_authenticated:
        current_ju = request.user.active_ju()
    else:
        current_ju = Ju.active_ju()
    return render_home_page(request, current_ju)
    
def view_list(request, list_id):
    list_ = List.objects.filter(id = list_id).first()
    if not list_:
        return redirect(reverse('home'))

    if list_.ju:
        return view_order(request, list_id)

    form = ExistingListItemForm(for_list = list_)

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            if form.save():
                return redirect(list_)
    if request.user.is_authenticated:
        return render(
            request, 
            'list.html', 
            { 'list': list_, 'form': form}
        )

    email_input_form = EmailInputForm()
    return render(
        request, 
        'list.html', 
        { 'list': list_, 'form': form, 'email_input_form': email_input_form}
    )


# type url manually ! '/lists/load_users/{ju_id}
def load_users(request, ju_id):
    ju = Ju.objects.get(id = ju_id)
    if ju.owner:
        if request.user != ju.owner:
            return redirect(reverse('home'))

    form = UsersForm()
    form.fields['content'].initial = '\n'.join(
        ['{};{};{}'.format(row.email,row.depart_name,row.display_name) for row in User.objects.all()]
    )

    if request.method == 'POST':
        form = UsersForm(data=request.POST)
        if form.is_valid():
            form.load_users()

    return render(request, 'load_users.html', {  'form': form, 'current_ju': ju})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>凑单吧</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>
	<body>
	<div class="container">
	    <nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
		    {% if user.is_authenticated %}
		      <div class="nav navbar-left">
		      <a href="/accounts/profile">
		        <img src="{{user.avatar}}" style="height:38px;width:38px" class="img-rounded">
		      </a>
	                账号： {{ user.display_name }}@{{user.depart_name}} 
		        <a href="{% url 'logout' %}">注销</a>
		      </div>
		    {% else %}
		      <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
			<span>请用邮箱登录:</span>
			{{ email_input_form.email }}
			<input type="submit" class="btn btn-primary mx-sm-2" value="发送" />
			{% csrf_token %}
			  {% if email_input_form.errors %}
			      <div class="form-group has-error">
			  	<span class="help-block">
					{{ email_input_form.email.errors }}
				</span>
			      </div>
			  {% endif%}
		      </form>
		    {% endif %}
		</div>
	    </nav>
	    {% if messages %}
	        <div class="row">
		    <div class="col-md-8">
			{% for message in messages %}
			    {% if message.level_tag == 'success' %}
			        <div class="alert alert-success">{{ message }}</div>
			    {% else %}
			        <div class="alert alert-warning">{{ message }}</div>
			    {% endif %}
			{% endfor %}
		    </div>
		</div>
	    {% endif %}
	    <div class="row">
		<div class="col-md-6 col-md-offset-3 jumbotron">
		    <div class="text-center">

{% block nav_tabs %}
<ul class="nav nav-tabs" id="myTab">
  <li><a href="{% url 'home' %}">活动</a></li>
  <li><a href="{% url 'category' %}">产品目录</a></li>
  <li><a href="{% url 'profile' %}">设置</a></li>
</ul>
{% endblock %}
		        <h4>{% block header_text %}{% endblock %}</h4>
{% block forms_before %}
{% endblock %}
{% block ju_table %}
  {% if current_ju %}
    {% if current_ju.ju_type != 'category' %}
    <h3>
    活动发起人：{{ current_ju.owner.display_name }}<br/>
    活动说明：{{ current_ju.address }}&nbsp 
    @{{ current_ju.location.name }}<br/>
    截止时间：{{ current_ju.stop_date_time|date:'Y-m-d H:i' }}<br/>
    活动状态：{{ current_ju.status_name }}    
    </h3>
    <h3><a href={% url 'next_ju' current_ju.id %}>换一个</a> &nbsp
    {% if request.user.is_authenticated %}
    <a href={% url 'list_jus' %}>活动列表</a> &nbsp
    <a href={% url 'new_ju' %}>发起活动</a>
    	{% if not current_ju.parent %}
    <a href={% url 'new_ju' p_id=current_ju.id %}>发起子活动</a>
    	{% endif %}
    {% endif %}
    </h3>
    {% else %}
    <h3>
    联系人：{{ current_ju.owner.display_name }}<br/>
    报价说明：{{ current_ju.address }}<br/>
    状态：{{ current_ju.status_name }}    
    </h3>
    <h3><a href={% url 'next_category' current_ju.id %}>换一个</a> &nbsp
    {% if request.user.is_authenticated %}
    <a href={% url 'list_categories' %}>产品报价列表</a> &nbsp
    <a href={% url 'new_ju' p_id=current_ju.id %}>发起活动</a>
    {% endif %}
    </h3>
 
    {% endif %}
    <table id="id_ju_table" class="table">
        <tr>
		<th style='text-align: center;'>代号</th>
		<th style='text-align: center;'></th>
		<th style='text-align: center;'>说明</th>
		<th style='text-align: center;'>单价</th>
		<th style='text-align: center;'>总单数</th>
	</tr>
    {% for k,v in current_ju.sorted_items %}
	<tr>
		<td style='text-align: left;'>{{ k }}
		</td>
		<td style='text-align: left;'>
	{% if v.images %}
	<a href="{{v.images.0}}"><img src="{{v.images.0}}" style="height:38px;"></a>
    	{% endif %}
		</td>
		<td style='text-align: center;'>
			{% if v.href %}
			<a href="{{v.href}}" target="_blank">
				{{ v.desc }}
			</a>
			{% else %}
				{{ v.desc }}
			{% endif %}
		</td>
		<td style='text-align: right;'>{{ v.price|floatformat:2 }} </td>
		<td style='text-align: right;'>{{ v.qty_family_sum|floatformat:2 }} </td>
	</tr>
    {% endfor %}
    </table>
  {% endif %}
{% endblock %}
{% block forms %}
{% endblock %}
	    </div>
		</div>
            </div>
	    <div class="row">
		<div class="col-md-6 col-md-offset-3">
		        {% block table %}
		        {% endblock %}
		</div>
	    </div>
	    <div class="row">
		<div class="col-md-6 col-md-offset-3">
		        {% block extra_content %}
		        {% endblock %}
		</div>
	    </div>
	</div>`
	<script src="/static/jquery-3.2.1.min.js"></script>
	<script src="/static/list.js"></script>
	<script>
$(document).ready(function(){
    window.Superlists.initialize();
});
	</script>
	</body>
</html>

lists/templates/home.html
{% extends 'list_base.html' %}
{% block header_text %}
{% if not request.user.is_authenticated %}
请扫码关注微信企业号。</br>根据企业助手通知，填写手机或邮箱进行验证。</br>企业号会出现在通讯录顶部，除凑单外，如还想尝试更多功能，建议下载和安装企业微信。
</br>
<img src='http://p.qpic.cn/pic_wework/2567071692/484ef640315e5fe228cb44e9a9fae9b21190a142bd4de522/0' style="height:258px;width:258px" class="img-rounded">
</br>
{% endif %}
{% if first_ju %}
<a href='{% url 'order' first_ju.id%}' >
      看看别人在凑什么
</a>
{% else %}
您关注的范围内没有活动，检查一下“设置”页，调整关注范围<br/>
或者尝试
{% endif %}
{% if request.user.is_authenticated %}
    &nbsp<a href={% url 'new_ju' %}>发起活动</a> 
    &nbsp<a href={% url 'list_jus' %}>活动列表</a> 
{% endif %}
<br/>
      自己凑个采购单！
{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}
{% block order_form %}
{% endblock %}
{% block ju_table %}
{% endblock %}

lists/templates/list.html
{% extends 'list_base.html' %}
{% block header_text %}
     凑着玩:{{ list.name }}
{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
{% block order_form %}
{% endblock %}
{% block table %}
	<table id="id_list_table" class="table">
		<tr>   
			<th style='text-align: left;'>名称</th>
			<th style='text-align: right;'>数量</th>
			<th style='text-align: right;'>单价</th>
			<th style='text-align: right;'>金额</th>
		</tr>
	    {% for item in list.item_set.all %}
		    <tr>
			<td style='text-align: left;'>{{ forloop.counter }}: {{ item.name}}</td>
		        <td style='text-align: right;'>{{ item.qty|floatformat:2}}</td>
		        <td style='text-align: right;'>{{ item.price|floatformat:2}}</td>
			<td style='text-align: right;'>{{ item.cost|floatformat:2 }}</td>
		    </tr>
	    {% endfor %}
	        <tr>
			<th></th><th></th>
			<th style='text-align: right;'>总价：</th>
			<th style='text-align: right;'>{{ list.total_cost|floatformat:2 }}</th>
		</tr>
	</table>
{% endblock %}

lists/templates/list_base.html
{% extends 'base.html' %}

{% block nav_tabs %}
{% block nav_tabs_lists %}
<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="{% url 'home' %}">活动</a></li>
  <li><a href="{% url 'category' %}">产品目录</a></li>
  <li><a href="{% url 'profile' %}">设置</a></li>
</ul>
{% endblock %}
{% endblock %}

{% block forms %}
{% block list_form %}
<form method="POST" action="{% block form_action %}{% endblock %}">
  <div class="form-inline"
    <div class="form_group">
    {{ form.text }}
    <input type="submit" class="btn btn-primary mx-sm-2" value="提交"  style="vertical-align:-8px;" />
    </div>
  </div>
   {% csrf_token %}
    {% if form.errors %}
      <div class="form-group has-error">
  	<span class="help-block">
	{{ form.text.errors }}
	</span>
      </div>
    {% endif %}
</form>
{% endblock %}
{% block order_form %}
<form method="POST" action="{% block order_form_action %}{% endblock %}">
  {% block new_agent_form_inputs %}
  <div class="form-inline">
    <div class="form-group">
      <label for="{{form_list.owner.id_for_label}}">{{form_list.owner.label}}</label>
      {{ form_list.owner }}
    </div>
  </div>
  {% endblock %}
  <div class="form-inline">
    <div class="form_group">
    {{ form.text }}
    <input type="submit" class="btn btn-primary mx-sm-2" value="提交"  style="vertical-align:-8px;" />
    </div>
  </div>
   {% csrf_token %}
    {% if form.errors %}
      <div class="form-group has-error">
  	<span class="help-block">
	{{ form.text.errors }}
	{{ form_list.owner.errors }}
	</span>
      </div>
    {% endif %}
</form>
{% endblock %}
{% endblock %}
	

lists/templates/load_users.html
{% extends 'ju_base.html' %}
{% block header_text %}邮箱授权{% endblock %}
{% block ju_table %}
{% endblock %}

{% block location_form %} {% endblock %}
{% block ju_form_action %} {% url 'load_users' current_ju.id %} {% endblock %}
{% block ju_form_inputs %}
{% endblock %}
{% block load_users_form_inputs %}
	{{form.content}}
{% endblock %}

lists/templates/manage_jus.html
{% extends 'base.html' %}
{% block header_text %}新建凑单活动{% endblock %}
{% block form_action %} {% url 'manage_jus' owner.email %} {% endblock %}
{% block submit_button %}<br/><input type="submit" value="Submit"> {% endblock %}
{% block extra_content %}
    <h2>账号：{{ owner.email }}创建的活动</h2>
    <ul>
	{% for ju in owner.ju_set.all %}
	<li><a href="{{ ju.get_absolute_url}}">{{ju.name}}（{{ju.status}}）</a></li>
	{% endfor %}
    </ul>
{% endblock %}

lists/templates/my_lists.html
{% extends 'list_base.html' %}
{% block header_text %}我的凑单{% endblock %}
{% block list_form %}{% endblock %}
{% block order_form %}{% endblock %}
{% block extra_content %}
    <h2>账号：{{ owner.email }}的凑单</h2>
    <h3>群组名称：{{ owner.depart_name }}</h3>
    <ul>
	{% for list in owner.list_set.all %}
	    <li><a href="{{ list.get_absolute_url}}">{{list.name}}</a></li>
	{% endfor %}
    </ul>
{% endblock %}

lists/templates/new_order.html
{% extends 'list_base.html' %}
{% block header_text %}
{% endblock %}
{% block list_form %}
{% endblock %}
{% block order_form_action %}{% url 'order' current_ju.id %}{%endblock %}

lists/templates/view_category.html
{% extends 'list_base.html' %}
{% block nav_tabs_lists %}
<ul class="nav nav-tabs" id="myTab">
  <li><a href="{% url 'home' %}">活动</a></li>
  <li class="active"><a href="{% url 'category' %}">产品目录</a></li>
  <li><a href="{% url 'profile' %}">设置</a></li>
</ul>
{% endblock %}
{% block header_text %}
  {% if current_ju %}
  	产品报价不能直接下单，找到你需要的产品，发起凑单活动后下单,每项产品的提货时间和提货方式请和报价联系人确认。
  {% else %}
  目前没有产品报价，试着自己
  <a href="{% url 'new_ju' %}">发布一个产品报价</a>
  {% endif %}
	
{% endblock %}

{% block list_form %}
{% endblock %}
{% block order_form %}{% endblock %}
{% block table %}
{% endblock %}

lists/templates/view_order.html
{% extends 'list_base.html' %}
{% block header_text %}
	{% if list.agent and list.agent != list.owner %}
	订单代理人：{{list.agent.display_name}}
	{% endif %}
{% endblock %}

{% block list_form %}
{% endblock %}
{% block order_form_action %}{% url 'view_order' list.id %}{% endblock %}
{% block new_agent_form_inputs %}
{% endblock %}
{% block table %}
    <table id="id_orders_table" class="table">
        <thead class="thead-inverse">
	<tr>
                <th style='text-align: center'>订单类型</th>
                <th style='text-align: center'>账号名称\代号</th>
                {% for k,v in list.ju.sorted_items %}
                <th style='text-align: right'>{{k}} </th>
                {% endfor%}
		<th style='text-align: right'>
		    <a href="{% url 'new_order' current_ju.id %}" class="btn btn-info">下单/代理</a>
		</th>
        </tr>
	</thead>
        <tr class="table-success">
		<th style='text-align: center'>
		    {% if not list.agent or list.agent == list.owner %}
		    	本人
                    {% else %}
		        代理	
                    {% endif %}
		</th>
		<th style='text-align: center'>{{ list.owner.display_name }}</th>
                {% for qty in list.qtys_by_ju %}
                <th style='text-align: right'>{{qty|floatformat:-2}}</th>
                {% endfor%}
                <th style='text-align: right'>{{list.total_cost|floatformat:2}}</th>
        </tr>
        {% for list_ in orders %}
	{% if list_ != list %}
        <tr class="table-success">
		<td style='text-align: center'>
		    <a href="{% url 'view_list' list_.id %}">
		    {% if not list_.agent or list_.agent == list_.owner %}
		    	本人
                    {% else %}
		        代理	
                    {% endif %}
		    </a>
		</td>
		<td style='text-align: center'>{{ list_.owner.display_name }}</td>
                {% for qty in list_.qtys_by_ju %}
                <td style='text-align: right'>{{qty|floatformat:-2}}</td>
                {% endfor%}
                <td style='text-align: right'>{{list_.total_cost|floatformat:2}}</td>
        </tr>
        {% endif %}
        {% endfor %}
    </table>
{% endblock %}